Repository sylabs/singularity, pull requests merged in 2021-11, with the labels that each got.

#395 feat: support for multi-part concurrent library image download
  CHANGELOG.md
  e2e/pull/concurrency.go
  e2e/pull/pull.go
  go.mod
  go.sum
  internal/pkg/client/library/library.go
  internal/pkg/client/library/pull.go
  internal/pkg/client/progress.go
  pkg/util/singularityconf/config.go
  pkg/util/singularityconf/parser_test.go
Labels: enhancement, ci:e2e

#399 Split SIF/bare types w.r.t `allow container $type` config
  CHANGELOG.md
  e2e/config/config.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/image/image.go
  pkg/util/singularityconf/config.go
Labels: enhancement, ci:e2e

#404 Flip RunAsRoot->UserNS in RPC for NvCCLI
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
Labels: ci:e2e

#410 fix: Don't truncate config file until we have valid output to write
  CHANGELOG.md
  internal/app/singularity/config_global_linux.go
Labels: bug, ci:e2e

#415 Omit progress bar on redirected output
  internal/app/singularity/push.go
  internal/pkg/client/library/pull.go
Labels: ci:e2e

#417 e2e: ensure GPU tests use intended profile
  e2e/gpu/gpu.go
Labels: testing

#422 no longer set python=3 for conda
  e2e/env/regressions.go
Labels: ci:e2e

#429 build(deps): bump github.com/sylabs/sif/v2 from 2.2.3 to 2.3.0
  go.mod
  go.sum
Labels: dependencies

#430 docs: Update CHANGELOG.md and README.md for 3.9.0
  CHANGELOG.md
  INSTALL.md
Labels: documentation

#438 Switch to containers/common from seccomp/containers-golang
  CHANGELOG.md
  etc/seccomp-profiles/default.json
  go.mod
  go.sum
  internal/pkg/runtime/engine/config/oci/config.go
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/security/seccomp/seccomp_supported.go
  internal/pkg/security/seccomp/seccomp_supported_test.go
  internal/pkg/security/seccomp/seccomp_unsupported.go
  internal/pkg/security/security.go
Labels: enhancement, dependencies

#443 dependencies: Update oras-go to v1.0.0
  examples/plugins/cli-plugin/go.sum
  examples/plugins/config-plugin/go.sum
  examples/plugins/log-plugin/go.sum
  examples/plugins/ubuntu-userns-overlay-plugin/go.sum
  go.mod
  go.sum
Labels: dependencies

#444 dependencies: Update oras-go to v1.0.0 (release-3.9)
  examples/plugins/cli-plugin/go.mod
  examples/plugins/cli-plugin/go.sum
  examples/plugins/config-plugin/go.sum
  examples/plugins/log-plugin/go.sum
  examples/plugins/ubuntu-userns-overlay-plugin/go.sum
  go.mod
  go.sum
Labels: dependencies

#449 e2e: check more output of plugin commands
  e2e/plugin/plugin.go
Labels: ci:e2e
