Repository sylabs/singularity, pull requests merged in 2023-07, with the labels that each got.

#1873 e2e: In actionOCiOverlayTeardown, show mount table differences
  e2e/actions/oci.go
Labels: ci:e2e, testing

#1883 oci: re-exec as early as possible
  cmd/internal/cli/actions.go
  cmd/internal/cli/singularity.go
  internal/pkg/util/rootless/rootless.go
Labels: techdebt

#1882 oci: switch direct run/shell/exec from URI to oci-sif flow
  CHANGELOG.md
  cmd/internal/cli/actions.go
  e2e/actions/oci.go
  internal/pkg/build/oci/fetch.go
  internal/pkg/client/oci/ocisif.go
  internal/pkg/client/oci/pull.go
Labels: enhancement

#1884 e2e: oci: oras push/pull/run
  CHANGELOG.md
  e2e/actions/oci.go
  e2e/internal/e2e/env.go
  e2e/internal/e2e/image.go
  e2e/pull/pull.go
  e2e/push/push.go
  e2e/suite.go
Labels: enhancement

#1891 oras: fix push of oci-sif
  internal/pkg/client/oras/oras.go
Labels: bug

#1889 oci: Handle oci-sif image refs without oci-sif: prefix
  e2e/actions/oci.go
  internal/pkg/runtime/launcher/oci/launcher_linux.go
  internal/pkg/runtime/launcher/oci/launcher_linux_test.go
  test/images/empty.oci.sif
Labels: enhancement

#1907 chore: Remove VM / SyOS code
  CHANGELOG.md
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions.go
  cmd/internal/cli/instance_start_linux.go
  cmd/internal/cli/startvm.go
Labels: techdebt

#1911 chore: Move library push impl to internal/pkg/client/library
  cmd/internal/cli/push.go
  internal/app/singularity/push.go
  internal/pkg/client/library/push.go
  internal/pkg/client/progress.go
Labels: techdebt

#1906 oci: Execute non-oci SIF in --oci mode
  cmd/internal/cli/actions.go
  cmd/internal/cli/instance_start_linux.go
  e2e/actions/oci.go
  internal/pkg/runtime/launcher/launcher.go
  internal/pkg/runtime/launcher/launcher_test.go
  internal/pkg/runtime/launcher/native/launcher_linux.go
  internal/pkg/runtime/launcher/oci/launcher_linux.go
  internal/pkg/runtime/launcher/oci/launcher_linux_test.go
  internal/pkg/runtime/launcher/oci/process_linux.go
  internal/pkg/runtime/launcher/oci/process_linux_test.go
  pkg/image/image.go
  pkg/image/sif.go
  pkg/ocibundle/sif/bundle_linux.go
  pkg/ocibundle/sif/bundle_linux_test.go
Labels: enhancement

#1917 push: OCI-SIF to docker:// OCI registries
  LICENSE_THIRD_PARTY.md
  cmd/internal/cli/pull.go
  cmd/internal/cli/push.go
  e2e/push/push.go
  go.mod
  internal/pkg/client/oci/auth.go
  internal/pkg/client/oci/ocisif.go
  internal/pkg/client/oci/push.go
Labels: enhancement

#1905 move keyserver-related cmds from `remote` to their own cmd
  CHANGELOG.md
  cmd/internal/cli/keyserver.go
  cmd/internal/cli/remote.go
  docs/keyserver.go
  docs/remote.go
  e2e/keyserver/keyserver.go
  e2e/remote/remote.go
  e2e/suite.go
  internal/app/singularity/keyserver_add.go
  internal/app/singularity/keyserver_list.go
  internal/app/singularity/keyserver_login.go
  internal/app/singularity/keyserver_logout.go
  internal/app/singularity/keyserver_remove.go
  internal/app/singularity/remote_list.go
Labels: enhancement

#1923 fix: Remove Warningf of credential in oci-sif docker:// push
  internal/pkg/client/oci/auth.go
Labels: bug

#1928 chore: refactor library token/identity to i/p/c/library
  cmd/internal/cli/remote.go
  internal/app/singularity/remote_get_login_password.go
  internal/app/singularity/remote_status.go
  internal/app/singularity/user.go
  internal/pkg/client/library/user.go
  internal/pkg/client/library/user_test.go
Labels: techdebt

#1929 remote: Make registryUri available for library
  internal/pkg/remote/endpoint/client.go
  internal/pkg/remote/endpoint/client_test.go
  internal/pkg/remote/endpoint/service.go
  test/remote/config.example.json
Labels: techdebt

#1935 chore: remove pkg/ociruntime
  e2e/oci/oci.go
  pkg/ociruntime/ociruntime.go
Labels: techdebt

#1936 chore: move pkg/sypgp to internal/pkg/sypgp
  cmd/internal/cli/key_export.go
  cmd/internal/cli/key_import.go
  cmd/internal/cli/key_list.go
  cmd/internal/cli/key_newpair.go
  cmd/internal/cli/key_newpair_test.go
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/key_push.go
  cmd/internal/cli/key_remove.go
  cmd/internal/cli/key_search.go
  cmd/internal/cli/pgp.go
  cmd/internal/cli/sign.go
  e2e/internal/e2e/ecl_key.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/signature/sign.go
  internal/pkg/signature/sign_test.go
  internal/pkg/signature/verify.go
  internal/pkg/sypgp/keyring.go
  internal/pkg/sypgp/select.go
  internal/pkg/sypgp/sypgp.go
  internal/pkg/sypgp/sypgp_test.go
  internal/pkg/sypgp/testdata_test.go
Labels: techdebt

#1953 fix: correct rpm/deb builds for squashfuse bundling
  .circleci/config.yml
  INSTALL.md
  debian/control
  debian/singularity-ce.install
  dist/rpm/singularity-ce.spec.in
  mlocal/checks/project-post.chk
  mlocal/frags/build_conmon.mk
  mlocal/frags/build_squashfuse.mk
Labels: bug

#1922 deps: replace oras-go
  CHANGELOG.md
  LICENSE_DEPENDENCIES.md
  e2e/cmdenvvars/cmdenvvars.go
  e2e/internal/e2e/dockerhub_auth.go
  e2e/pull/pull.go
  e2e/registry/registry.go
  go.mod
  go.sum
  internal/pkg/client/ocisif/auth.go
  internal/pkg/client/ocisif/ocisif.go
  internal/pkg/client/oras/image.go
  internal/pkg/client/oras/layer.go
  internal/pkg/client/oras/oras.go
  internal/pkg/client/oras/pull.go
  internal/pkg/remote/credential/login_handler.go
Labels: techdebt, dependencies
